site_name: OpenPonk
site_description: OpenPonk software and business modeling platform
site_author: Peter Uhnák

repo_url: https://github.com/openponk/openponk/
repo_name: 'GitHub'

remote_name: https://github.com/openponk/openponk.github.io/

pages:
    - OpenPonk: index.md
    - Development:
        - Installation: dev/installation.md
        - Overview: dev/overview.md
        - GUI: dev/gui.md
        - 'New plugin': dev/plugin.md
        - Navigator: dev/navigator.md
        - 'Extending menus': dev/menus.md
        - Palette: dev/palette.md
        - Form: dev/form.md
#theme: readthedocs
#theme: mkdocs
#theme: cosmo
theme_dir: themes/mkdocs_bootswatch/cosmo


google_analytics: ['UA-74827338-2', 'dynacase.github.io']

copyright: |
    <a href="https://www.elixir-czech.cz" target="_blank"><img src="/elixir-cz-logo.png" height="100" />OpenPonk is a registered Elixir CZ tool</a>
    <span style="border-left: 2px solid gray; line-height: 50px; margin: 20px; padding: 20px 0 20px 20px"></span>
    <a href="https://www.formetis.nl" target="_blank">Sponsored by <img src="/formetis-logo.jpg" height="50" /></a>
    <br>
    <br>
    <a href="mailto:openponk@gmail.com"><span class="fa fa-envelope"></span> openponk@gmail.com</a>
    <span class="point"> · </span>

            <a href="https://github.com/dynacase/dynacase"><span class="fa fa-github"></span> Github</a>

            <span class="point"> · </span>
            <span>OpenPonk</span>
            <span class="point"> · </span>
            <span>Copyright &copy; 2014 Peter Uhnák, Robert Pergl</span>
            <span class="point"> · </span>
            <a href="http://ccmi.fit.cvut.cz/" rel="noreferrer">
                  <span class="icon">
                      <img src="/CCMi-logo_512.png" alt="logo" style="max-height:17px">
                  </span>
                CCMi FIT ČVUT
                <span></span>
            <br><br>
