site_name: DynaCASE
site_description: DynaCASE software and business modeling platform
site_author: Peter Uhnák
copyright: '&copy; 2014, 2016 Peter Uhnák &gt;i.uhnak(at)gmail.com&lt;'

repo_url: https://github.com/dynacase/dynacase/
repo_name: 'GitHub'

remote_name: https://github.com/dynacase/dynacase.github.io/

pages:
    - DynaCASE: index.md
    - FSM: fsm/fsm.md
    - UML: uml/uml.md
    - BORM: borm/borm.md
    - Development:
        - Installation: dev/installation.md
        - Overview: dev/overview.md
        - GUI: dev/gui.md
        - 'New plugin': dev/plugin.md
        - Navigator: dev/navigator.md
        - 'Extending menus': dev/menus.md
        - Palette: dev/palette.md
        - Form: dev/form.md
#theme: readthedocs
#theme: mkdocs
#theme: cosmo
theme_dir: themes/mkdocs_bootswatch/cosmo


google_analytics: ['UA-74827338-2', 'dynacase.github.io']

copyright: |
    <a href="mailto:i.uhnak(at)gmail.com"><span class="fa fa-envelope"></span> i.uhnak(at)gmail.com</a>
    <span class="point"> · </span>

            <a href="https://github.com/dynacase/dynacase"><span class="fa fa-github"></span> Github</a>

            <span class="point"> · </span>
            <span>DynaCASE</span>
            <span class="point"> · </span>
            <span>Copyright &copy; 2014 Peter Uhnák, Robert Pergl</span>
            <span class="point"> · </span>
            <a href="http://ccmi.fit.cvut.cz/" rel="noreferrer">
                  <span class="icon">
                      <img src="/CCMi-logo_512.png" alt="logo" style="max-height:17px">
                  </span>
                CCMi FIT ČVUT
                <span></span>
            <br><br>

